{
 "title": "Mailman3 Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Member Count Per List",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mailman3_list_members_total", "legendFormat": "{{list}}" }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mailman3_users_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Mailman3 List Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "mailman3_lists", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mailman3 Queue Size",
   "type": "timeseries",
   "description": "messages per queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "mailman3_queues", "legendFormat": "{{queue}}" }
   ]
  }
 ]
}