{
 "title": "Management Daemon Status",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(kube_service_info{service=~\".*-daemon\"}, service)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(management_daemon_command_exit{service=\"$service\"}, exported_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "$job runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "management_daemon_command_duration{exported_job=~\"$job\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "$job exit status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "management_daemon_command_exit{exported_job=~\"$job\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(canvas_event_count{external_job=~\"$job\"}[5m])",
     "legendFormat": "{{ source }}"
    }
   ]
  }
 ]
}