{
 "title": "Memcached Capacity",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{service=~\".*-memcached\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memcached Connection Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (memcached_current_connections{service=\"$service\"} / memcached_max_connections{service=\"$service\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "hit rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "(sum (memcached_commands_total{status=\"hit\",command=\"get\",service=~\"$service\"}) / sum (memcached_commands_total{command=\"get\",service=~\"$service\"})) * 100",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "get/set ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "100 * (sum (memcached_commands_total{command=\"get\",service=~\"$service\"}) / (sum (memcached_commands_total{command=\"get\",service=~\"$service\"}) + sum (memcached_commands_total{command=\"set\",service=~\"$service\"})))",
     "legendFormat": "get"
    }
   ]
  },
  {
   "title": "Memory Use per Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "memcached_current_bytes{service=\"$service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(100 * (memcached_current_bytes{service=~\"$service\"} / memcached_limit_bytes{service=~\"$service\"}))",
     "legendFormat": "capacity %"
    }
   ]
  },
  {
   "title": "Aggregate Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{service=~\"$service\"})",
     "legendFormat": "bytes used"
    },
    {
     "expr": "sum(memcached_limit_bytes{service=~\"$service\"} - memcached_current_bytes{service=~\"$service\"})",
     "legendFormat": "bytes free"
    }
   ]
  },
  {
   "title": "Command rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{command=\"get\",service=\"$service\"}[1m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(memcached_commands_total{command=\"set\",service=\"$service\"}[1m]))",
     "legendFormat": "set"
    },
    {
     "expr": "sum(rate(memcached_commands_total{command=\"flush\",service=\"$service\"}[1m]))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Cache Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_current_items{service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(memcached_current_items{service=~\"$service\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}