{
 "title": "Restclients Health",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{namespace!~\"(kube|mci|gke|cert|ingress)-.*\"},namespace)"
    }
   },
   { "name": "job_label", "label": "Service", "query": "App : job, Job : exported_job" },
   {
    "name": "job",
    "label": "Workload",
    "query": {
     "query": "label_values(restclient_response_status_code_count{namespace=\"$namespace\", $job_label!~\".*pushgateway\"},$job_label)"
    }
   },
   {
    "name": "exported_service",
    "label": "Restclient",
    "query": {
     "query": "label_values(restclient_response_status_code_count{namespace=\"$namespace\", $job_label=\"$job\"},exported_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Restclient Request Rate (/min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(restclient_response_status_code_count{namespace=\"$namespace\",$job_label=\"$job\"}[1m])) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "$exported_service reponse time (sec)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(restclient_request_duration_seconds_bucket{namespace=\"$namespace\",$job_label=\"$job\",exported_service=\"$exported_service\"}[1m])) by (le)",
     "legendFormat": "$exported_service"
    }
   ]
  },
  {
   "title": "$exported_service response status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"100(.0)?\"}[1m]))",
     "legendFormat": "100"
    },
    {
     "expr": "sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"200(.0)?\"}[1m])) - sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"100(.0)?\"}[1m]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"300(.0)?\"}[1m])) - sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"200(.0)?\"}[1m]))",
     "legendFormat": "300"
    },
    {
     "expr": "sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"400(.0)?\"}[1m])) - sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"300(.0)?\"}[1m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"500(.0)?\"}[1m])) - sum(rate(restclient_response_status_code_bucket{exported_service=\"$exported_service\",$job_label=\"$job\",namespace=\"$namespace\",le=~\"400(.0)?\"}[1m]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "$exported_service Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(restclient_request_timeout_total{namespace=\"$namespace\",$job_label=\"$job\",exported_service=\"$exported_service\"}) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}