{
 "title": "Vax Status Notifications",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vax Status Notification Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "notifications/min" }
   ],
   "targets": [
    {
     "expr": "rate(status_notification_count_total{service=~\"vax-status-listener-prod-(prod|test)\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gross Notification Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "notifications/min" }
   ],
   "targets": [
    {
     "expr": "rate(notification_count_total{service=~\"vax-status-listener-prod-(prod|test)\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Invalid Notification Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "notifications/min" }
   ],
   "targets": [
    {
     "expr": "rate(invalid_notification_count_total{service=~\"vax-status-listener-prod-(prod|test)\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ignored Notification Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "notifications/min" }
   ],
   "targets": [
    {
     "expr": "rate(ignored_notification_count_total{service=~\"vax-status-listener-prod-(prod|test)\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}